### ISSUE TITLE
Using sigmoid(rgb) or clamp(rgb) is correct?

### ISSUE THREAD

**Issue by lukasHoel** [sarafridov/plenoxels#10]
Hi,

thanks for your awesome work!
in the Plenoctree paper and in this implementation, you apply the sigmoid function to the SH sum:
https://github.com/sarafridov/plenoxels/blob/975d2619a75b4e6fadd8b72e9edbf30fdf7e559c/plenoxel.py#L38 

Whereas in the CUDA implementation it seems to me like you apply clamp(x+0.5, 0, inf):
https://github.com/sxyu/svox2/blob/59984d6c4fd3d713353bafdcb011646e64647cc7/svox2/csrc/render_lerp_kernel_cuvol.cu#L102 
`outv += weight * fmaxf(lane_color_total + 0.5f, 0.f);  // Clamp to [+0, infty)`

What's the reason for the different implementations and which is more accurate?
If it is the second one: why do you add constant 0.5f, whats the intuition for this factor?

Thanks a lot! :)

**Comment by sarafridov** [comment]
Good eye! The short answer is that we changed it from sigmoid to just clamp in an attempt to be more physically accurate, with the idea being that actual radiance is unbounded above and the clipping to [0,1] happens at the camera sensor. The 0.5 constant was just to make the default starting color gray rather than black, but it's not too important. This sigmoid vs clamp doesn't seem to make much difference; both versions work ok in practice. Feel free to play around with it :)

**Comment by lukasHoel** [comment]
Thank you very much for clarifying!
