### ISSUE TITLE
"self.use_sphere_bound" appears twice in definition.

### ISSUE THREAD

**Issue by PSGLGDnoChampion** [sarafridov/plenoxels#7]
Hi, thanks for your work.
There is a sentence I cannot understand in "opt/util/dataset_base.py".
def __init__(self):
        self.ndc_coeffs = (-1, -1)
        self.use_sphere_bound = False
        self.should_use_background = True # a hint
        self.use_sphere_bound = True
As above, **self.use_sphere_bound** appears twice. Is it a mistake?

**Comment by sarafridov** [comment]
I think you're referring to the CUDA repository, here: https://github.com/sxyu/svox2. If you're working with an unbounded scene then yes, you want to use the sphere bound so that the foreground and background align properly; for a bounded scene either way is ok. Probably the duplication is just a typo leftover from experimenting with different versions.
